version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=car_service
    ports:
      - '5432:5432'

  car-service:
    container_name: car_service_app
    pull_policy: always
    build:
      context: CarService
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/car_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abc
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - psql-db
