version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car_service
    ports:
      - '5432:5432'
  car-service:
    container_name: car_service_app
    pull_policy: always
    build:
      context: CarService
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/car_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_PORT=5001
    depends_on:
      - psql-db
  frontend:
    container_name: frontend_app
    image: frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - car-service
